apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 20
  selector:
    matchLabels:
      app: myfrontend
  template:
    metadata:
      labels:
        app: myfrontend
    spec:
      containers:
        - name: myfrontend
          # 여러분의 image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_e6f79e6d8248